spring.application.name=demo
spring.server.port = 9089

#Logger level
logger.level.root = info

#Set the logging level for a specific package/class
logger.level.com.example.demo.configurationDB = trace

#Set appender
logger.appender.file.class= ch.qos.logback.core.FileAppender
logger.appender.file.path= /
logger.appender.file.name= loggerfile 
#Set logger pattern
logger.pattern.file = %d{dd/mm/YYYY} [%thread] %-5level %logger{36} -NSId=%X{nsId} %msg% /n

#Set file name
logger.file.name = loggerfile

#Set file path
logger.file.path = /

#Set file size
logger.file.max-size= 100MB

#Rolling policy
logger.file.rolling-policy.file-name-pattern = {logger.file-name} - %d{dd/mm/yy}
logger.file.rolling-policy.max-file-size= 100MB


#Security Credential
spring.security.user.name = root
spring.security.user.password = root

secret.key = abc

